### ISSUE TITLE
Diverging history breaks pulling on webhook

### ISSUE THREAD

**Issue by yeldiRium** [strangedev/neuron-buildbot#1]
Hi :wave: 

cool project you have here. I found a teeny little bug:

If i force push a change in my history - as I sometimes do when I find typos I made just seconds ago - the history in the remote diverges from the current state of the repo in the buildbot. When it then receives a webhook call, it tries to pull using a `fast-forward merge` - which obviously fails.

This is the error message I get:

```
[2020-12-02T19:55:04.214Z][Info] ❗ Received a push event.
[2020-12-02T19:55:04.997Z][Error] 💥 Cannot pull from https://git.staubwolke.org/yeldir/zettelkasten: CannotPullRepository: FastForwardError: A simple fast-forward merge was not possible.
```

I suggest to always force-pull, since the build bot never makes changes to its local repository. When it receives a webhook call, it should just get the current state from remote and disregard its own history, if it diverges.

Kind regards and I'll surely help out,
yeldiR

**Comment by yeldiRium** [comment]
We discussed throwing the repo away and re-cloning.

I think this is a bad idea, because

1. Over time it takes longer and longer to clone
2. We could not take advantage of neuron's cache and would have to re-build the entire zettelkasten every time
3. During building the previous output is gone and the frontend breaks temporarily

**Comment by strangedev** [comment]
Thanks for your issue 🥳 

Yes, I think cloning again should be a last resort only, for the reasons you've listed.

We've also discussed force-pulling as an alternative and I think it could be implemented rather easily.
There is, however, an issues with this approach which is rather subtle:

When we'd perfom a force pull, out-of-tree files would not be touched (which is precisely what we want for points 2 & 3).
This also means if you intend to delete a zettel by means of a history rewrite, since the buildbot already has a local copy, and the file is now out-of-tree, we would end up with an inconsistent state.

This might be fine. Maybe we should look for out-of-tree files outside of `.neuron` and delete them?

One one hand, I'd argue that history rewrites are not a legitimate tactic for deleting things in shared git environment.
On the other hand, when pushing to a public repository, I understand that there are legitimate cases where you'd want commits gone for good.

Do you have any additional thoughts on this?

**Comment by strangedev** [comment]
As we've discussed privately, having a local branch seems to create problems.
For now we will go with a third approach, which you came up with:

We ditch the local branch and work with a detached head which tracks the upstream directly.
This way, local copies are not persisted beyond the scope of what is present upstream.
With this approach, tracked files from deleted commits are also deleted locally, but generated, untracked files are not touched.

**Comment by strangedev** [comment]
It seems that the semantics in `isomorphic-git` differs from regular git semantics.
Checking out with a specific remote name passed to `checkout()` does not, in fact, create a detached head.

Thus, 4c461b0 does not fix this issue.
